<?php
/**
 * Copyright © MagoArab. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php 
// Simple debug
$writer = new \Zend\Log\Writer\Stream(BP . '/var/log/magoarab_debug.log');
$logger = new \Zend\Log\Logger();
$logger->addWriter($writer);
$logger->info('MagoArab BlockCustomer: Form template loaded');
$logger->info('MagoArab BlockCustomer: Form HTML: ' . $block->getFormHtml());
?>
<?php echo $block->getFormHtml() ?>